import { Matrice } from './matrice';

const posteUnset = [
  { zone: 3, ranger: 1, poste: 1 },
  { zone: 3, ranger: 1, poste: 2 },
  { zone: 3, ranger: 1, poste: 3 },
  { zone: 3, ranger: 1, poste: 4 },
  { zone: 4, ranger: 1, poste: 2 },
  { zone: 4, ranger: 1, poste: 3 },
  { zone: 4, ranger: 1, poste: 4 },
  { zone: 4, ranger: 1, poste: 6 },
  { zone: 4, ranger: 5, poste: 5 },
  { zone: 4, ranger: 5, poste: 4 },
  { zone: 4, ranger: 5, poste: 3 },
  { zone: 3, ranger: 5, poste: 3 },
  { zone: 4, ranger: 6, poste: 6 },
  { zone: 4, ranger: 6, poste: 4 },
  { zone: 4, ranger: 6, poste: 2 },
  { zone: 4, ranger: 7, poste: 2 },
  { zone: 4, ranger: 7, poste: 4 },
  { zone: 4, ranger: 7, poste: 6 },
  { zone: 3, ranger: 7, poste: 2 },
  { zone: 3, ranger: 7, poste: 4 },
  { zone: 3, ranger: 7, poste: 6 },
  { zone: 3, ranger: 8, poste: 2 },
  { zone: 3, ranger: 8, poste: 4 },
  { zone: 3, ranger: 8, poste: 6 },
  { zone: 3, ranger: 9, poste: 2 },
  { zone: 3, ranger: 9, poste: 3 },
  { zone: 3, ranger: 9, poste: 4 },
  { zone: 3, ranger: 9, poste: 6 },
  { zone: 3, ranger: 10, poste: 2 },
  { zone: 3, ranger: 10, poste: 4 },
  { zone: 3, ranger: 10, poste: 6 },
  { zone: 3, ranger: 11, poste: 2 },
  { zone: 3, ranger: 11, poste: 4 },
  { zone: 3, ranger: 11, poste: 6 },
  { zone: 3, ranger: 12, poste: 1 },
  { zone: 3, ranger: 12, poste: 2 },
  { zone: 3, ranger: 12, poste: 4 },
  { zone: 3, ranger: 12, poste: 6 },
  { zone: 3, ranger: 13, poste: 2 },
  { zone: 4, ranger: 8, poste: 2 },
  { zone: 4, ranger: 8, poste: 4 },
  { zone: 4, ranger: 8, poste: 6 },
  { zone: 4, ranger: 9, poste: 2 },
  { zone: 4, ranger: 9, poste: 3 },
  { zone: 4, ranger: 9, poste: 4 },
  { zone: 4, ranger: 9, poste: 6 },
  { zone: 4, ranger: 10, poste: 2 },
  { zone: 4, ranger: 10, poste: 4 },
  { zone: 4, ranger: 10, poste: 6 },
  { zone: 4, ranger: 11, poste: 2 },
  { zone: 4, ranger: 11, poste: 4 },
  { zone: 4, ranger: 11, poste: 6 },
  { zone: 4, ranger: 12, poste: 2 },
  { zone: 4, ranger: 12, poste: 4 },
  { zone: 4, ranger: 12, poste: 6 },
  { zone: 4, ranger: 13, poste: 1 },
  { zone: 4, ranger: 13, poste: 2 },
  { zone: 4, ranger: 13, poste: 3 },
  { zone: 4, ranger: 13, poste: 4 },
  { zone: 4, ranger: 13, poste: 6 },
  { zone: 1, ranger: 1, poste: 3 },
  { zone: 2, ranger: 1, poste: 3 },
  { zone: 1, ranger: 5, poste: 3 },
  { zone: 1, ranger: 5, poste: 4 },
  { zone: 2, ranger: 5, poste: 4 },
  { zone: 2, ranger: 6, poste: 1 },
  { zone: 2, ranger: 6, poste: 3 },
  { zone: 2, ranger: 6, poste: 5 },
  { zone: 2, ranger: 7, poste: 1 },
  { zone: 2, ranger: 7, poste: 3 },
  { zone: 2, ranger: 7, poste: 5 },
  { zone: 2, ranger: 7, poste: 7 },
  { zone: 2, ranger: 8, poste: 1 },
  { zone: 2, ranger: 8, poste: 3 },
  { zone: 2, ranger: 8, poste: 5 },
  { zone: 2, ranger: 8, poste: 7 },
  { zone: 2, ranger: 9, poste: 1 },
  { zone: 2, ranger: 9, poste: 3 },
  { zone: 2, ranger: 9, poste: 5 },
  { zone: 2, ranger: 9, poste: 7 },
  { zone: 2, ranger: 10, poste: 1 },
  { zone: 2, ranger: 10, poste: 3 },
  { zone: 2, ranger: 10, poste: 5 },
  { zone: 2, ranger: 10, poste: 7 },
  { zone: 2, ranger: 11, poste: 1 },
  { zone: 2, ranger: 11, poste: 3 },
  { zone: 2, ranger: 11, poste: 5 },
  { zone: 2, ranger: 11, poste: 7 },
  { zone: 2, ranger: 12, poste: 1 },
  { zone: 2, ranger: 12, poste: 3 },
  { zone: 2, ranger: 12, poste: 5 },
  { zone: 2, ranger: 12, poste: 7 },
  { zone: 1, ranger: 9, poste: 3 },
  { zone: 1, ranger: 11, poste: 2 },
  { zone: 1, ranger: 11, poste: 3 },
  { zone: 1, ranger: 11, poste: 4 },
  { zone: 1, ranger: 12, poste: 2 },
  { zone: 1, ranger: 12, poste: 4 },
];

export function setNonViablePostes(matrice: Matrice) {
  posteUnset.forEach((nvPoste) => {
    const { zone, ranger, poste } = nvPoste;
    if (matrice.zones[zone - 1] && matrice.zones[zone - 1].rangers[ranger - 1] && matrice.zones[zone - 1].rangers[ranger - 1].postes[poste - 1]) {
      const targetPoste = matrice.zones[zone - 1].rangers[ranger - 1].postes[poste - 1];
      if (!targetPoste.occupe) {
        targetPoste.viable = false;
      }
    }
  });
}
